### PR TITLE
Improve our logo

### PR DESCRIPTION
**Pull request by coderbyheart**
This PR adresses a few of the visual shortcomings I see in the logo:

 - the `i`-dot looks freakishly large
 - the `t` looks like like the christian cross `✝` and separates the `Fin` and `ura`

If changed the font in use from *Futura* to the free font [*Quicksand*](http://www.typophile.com/node/50437) which keeps the straight appearance but adds orientation by using more details. I've rebuild the symbol to have rounded edges in the same diameter of the font.

## Comparison

See [*Files changed*](https://github.com/fintura/gfx/pull/1/files) for interactive comparison.

### Old

Fintura Logo v1

### New

Fintura Logo v2

### CODE REVIEW

**Comment by gregoralbrecht** [comment]
Two things:
##### 1. Concerning this logo:
I do like the rounded edges on the symbol, but I really don't like the new font. I never liked Quicksand 
so maybe I'm biased. It's just really thin and imo doesn't work with the font of the tagline.
Imo it's much more important to fix the kerning issues:
kerning-issues

It should be optical kerning but I'm quite sure it's set on metrics.

##### 2. Responsive logo:
A couple of weeks ago, we noticed that this version - with the tagline - doesn't scale well. You can hardly read the tagline when the logo is small and it just looks cluttered. So we did an alt version:
logo_fintura_v2

We also tried to unify the use of whitespace around the logo:

logo_fintura_v2_whitespace

**Comment by coderbyheart** [comment]
Yes fixing the kerning issues helps a little. 
I also like the removal of the tagline. It also doesn't work well with the planned internationalization …

**Comment by coderbyheart** [comment]
@gregoralbrecht Can you do a new PR with your updated logo version?

**Comment by gregoralbrecht** [comment]
Sure! Will get on it after lunch!

**Comment by coderbyheart** [comment]
Closing as wontfix.

**Pull request closed without merging**
